---
title: "HW 2"
author: "Jonathan Li and Maya Lu"
date: "4/22/2021"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(patchwork)
library(gmodels)
library(tidyr)
library(metRology)

data <- read.table("videodata.txt", header=TRUE)
data_pt2 <- read.table("videoMultiple.txt", header=TRUE)
```

### 2.1 Fraction of Students who Played Video Games
* Point Estimate: 0.374
* Interval Estimate: (0.217, 0.53)
```{r}
N = 314 # population size
n = nrow(data) #sample size
correction = sqrt((N - n) / (N))

# point estimate: proportion of students who spent some time playing games
played <- data$time > 0
xbar <- mean(played)

# find standard error
sd.xbar <- sqrt(xbar * (1-xbar))
se <- (sd.xbar / sqrt(n-1)) * correction

# interval estimate: using 95 percent confidence
z = 1.96 #z-score for 95% confidence interval
width = z * sqrt( ( (xbar * (1- xbar) ) / (n-1) )
                    *( (N-n) / N )
                  )

int = c(xbar - width, xbar + width)
```

### 2.2 Fraction of Students who Played Games vs. Reported Frequency of Play

```{r}
prop.table(table(data$freq))
expected_frac <- 0.3076923 + 0.0989011
```


### 2.3 Average Time Spent Playing Video Games

* Point Estimate: 1.243
* Interval Estimate: (0.684, 1.801)

```{r}
N = 314
n = 91

# point estimate
xbar <-  mean(data$time)
se <- (sd(data$time) / sqrt(n))
  
# interval estimate
t = qt(0.025, df = 90, lower = F)
s = sd(data$time)

width = t * (s/sqrt(n)) 
int = c(xbar - width, xbar + width)

# interval estimate using simulation
reps = 100000
bootout = rep(NA, reps)

for (i in 1:reps){
  resample <- sample(data$time, size = n, replace = T)
  xbar <- mean(resample)
  bootout[i] <- xbar
}
t <- rt.scaled(100000, df = 90, mean = xbar, sd = se)
norm <- rnorm(100000, mean = xbar, sd = se)
df = data.frame(bootout, t, norm)

bootout.int <- quantile(bootout, c(0.025, .975))

ggplot(data = df, aes(x = bootout)) + 
  geom_histogram(aes(y = ..density..), bins = 30, alpha = 0.5, fill = "firebrick4") +
  ggtitle("Distribution of Average Time Spent Playing Video Games") +
  geom_vline(xintercept = int[1], linetype = "dashed", col = "dodgerblue") +
  geom_vline(xintercept = int[2], linetype = "dashed", col = "dodgerblue") +
  geom_vline(xintercept = bootout.int[1], linetype = "dotted", col = "red") +
  geom_vline(xintercept = bootout.int[2], linetype = "dotted", col = "red") +
  xlab("Hours Spent Playing Video Games") +
  geom_density(aes(x = t), col = "blue") + 
  theme_minimal()

quantile(bootout, c(0.025, .975))

mean(bootout <= int[1] |  bootout >= int[2])

# KS Test for T-Dist and Bootout
ks.test(bootout, t)

```


### 2.4 Reasons For Liking/Disliking Video Games

```{r}
prop.table(table(data$like))
data$enjoy <- 99
data$enjoy[data$like == 4 | data$like == 5] <- 0
data$enjoy[data$like == 2 | data$like == 3] <- 1

prop.table(table(data$enjoy))
prop.table(table(data$educ))

# bar graph of attitude questions
q1 <- c(6:10, 12)
q2 <- 13:20

# LIKE
# Top five reasons why they liked 
q1_props <- sort(colMeans(data_pt2[,q1], na.rm = T), decreasing = T)[1:5]
q1_props <- round(q1_props, 2)
labels <- c("Relaxation", "Feeling of Mastery", "Bored", "Graphics/Realism", "Mental Challenge")
df <- data.frame(labels, q1_props, row.names = labels)
reasons_like <- ggplot(df, aes(x= reorder(labels, -q1_props), y = q1_props)) + 
  geom_bar(stat = "identity", fill = "steelblue") +
  geom_text(aes(label = q1_props), vjust = -0.5) +
  theme_minimal() +
  xlab("") + ylab("Proportion") + ggtitle("Why do you play the games you checked above?")

#DISLIKE
# get top five reasons
q2_props <- sort(colMeans(data_pt2[,q2], na.rm = T), decreasing = T)[1:5]
q2_props <- round(q2_props, 2)

labels <- c("Too much time", "Costs too Much", "Pointless", "Frustrating", "Too many rules")
df <- data.frame(labels, q2_props)
reasons_dislike <- ggplot(df, aes(x= reorder(labels, -q2_props), y = q2_props)) + 
  geom_bar(stat = "identity", fill = "steelblue") +
  geom_text(aes(label = q2_props), vjust = -0.5) +
  theme_minimal() + ylim(c(0, 0.6))+
  xlab("") + ylab("Proportion") + ggtitle("What don't you like about video games?")

reasons_like + reasons_dislike
```



### 2.5 Differences Between Those Who Like and Dislike
``` {r}
gender = CrossTable(data$enjoy, data$sex)
own = CrossTable(data$enjoy, data$own)

# create an indicator if someone is working
data$works <- 0
data$works[data$work > 0] <- 1
work = CrossTable(data$enjoy, data$works)

# prop tests to check statistical significance
prop.test(table(data$enjoy, data$sex)[1:2,])
prop.test(table(data$enjoy, data$sex)[1:2,])
prop.test(table(data$works, data$enjoy)[,1:2])
```



```{r}
# function that returns a dataframe of distribution across variable of interest
create_bar <- function(cross_tab, binary, var_str) {
  df <- data.frame(prop = cross_tab$prop.col[,binary], row.names = c("disliked", "liked", "NA"))
  
  return (
    ggplot(data = df, aes(x= rownames(df), y = prop )) + 
      ylim(c(0, 1.0)) +
      geom_bar(stat = "identity", fill = "steelblue") + 
      xlab("") + ylab("Proportion") + ggtitle(paste(var_str,"Opinion on Video Games")) +
      theme_minimal() +  
      geom_text(aes(label = round(prop, 2)), vjust = -0.5) 
  )
}

create_bar2 <- function(cross_tab, binary, groups, var_str) {
  df <- data.frame(prop = cross_tab$prop.row[binary,], row.names = c(groups[1], groups[2]))
  
  return (
    ggplot(data = df, aes(x= rownames(df), y = prop )) + 
      ylim(c(0, 1.0)) +
      geom_bar(stat = "identity", fill = "steelblue") + 
      xlab("") + ylab("Proportion") + 
      ggtitle(paste("Distribution among those who", var_str, "Video Games")) +
      theme_minimal() +  
      geom_text(aes(label = round(prop, 2)), vjust = -0.5) 
  )
}

# bar graph: gender
female = create_bar(gender, "0", "Female")
male = create_bar(gender, "1", "Male")

disliked = create_bar2(gender, "0", c("female", "male"), "Disliked")
liked = create_bar2(gender, "1", c("female", "male"), "Liked")

(female + male) / (disliked + liked)

# bar graph: Own Computer
no_comp <- create_bar(own, "0", "Not Computer Owner")
has_comp <- create_bar(own, "1", "Computer Owner")

disliked = create_bar2(own, "0", c("no computer", "own computer"), "Disliked")
liked = create_bar2(own, "1", c("no computer", "own computer"), "Liked")

(no_comp + has_comp )/ (disliked + liked)

# bar graph: Works
not_worker <- create_bar(work, "0", "Not Employed")
worker <- create_bar(work, "1", "Employed")

disliked = create_bar2(work, "0", c("no work", "has work"), "Disliked")
liked = create_bar2(own, "1", c("no work", "has work"), "Liked")
(not_worker + worker) / (disliked + liked)
```

### 2.6 Grade Distribution

```{r}
obs_dist <- prop.table(table(data$grade))
to_append <- c(0)
names(to_append) <- c("1")
obs_dist <- c(obs_dist, to_append)

df <- data.frame(obs_dist, 
                 letter_grade = c("C", "B", "A", "D or Lower"),
                 tar_dist = c(.20, .30, .40, .10))
df <- gather(df, key = "dist", value = "freq", -letter_grade)

ggplot(df, aes(x = letter_grade, y = freq, fill = dist )) + 
  geom_bar(stat = "identity", position = "dodge")  +
  scale_fill_brewer(palette = "Paired", 
                    direction = -1, 
                    name = "Distribution", 
                    labels = c("Expected", "Target")) + 
  theme_minimal() +
  xlab("Letter Grade") + ylab("Proportion") + 
  ggtitle("Expected vs Target Grade Distribution") + ylim(c(0, 0.7)) + 
  geom_text(aes(label = round(freq, 2)), vjust = -0.5, position = position_dodge(0.9)) 


# chisq test
tar_dist = c(0.10, .20, .30, .40)
obs_dist <- sort(c(table(data$grade), to_append))
chisq.test(obs_dist, p= tar_dist, correct = F)

```

### 3 Advanced Analysis

```{r}

# average time across expected grades
mean_A = mean(data$time[data$grade == "4"])
mean_B = mean(data$time[data$grade == "3"])
mean_C = mean(data$time[data$grade == "2"])
mean_DF = mean(data$time[data$grade == "1"])
means = c(mean_A, mean_B, mean_C, mean_DF)
df = data.frame(means, labels = c("A", "B", "C", "D/F"))

# plot means
ggplot(df, aes(x = labels, y = means)) +
  geom_bar(stat = 'identity', fill = "steelblue") +
  theme_minimal()+
  ylab("Average Hours Spent Playing Games")+
  xlab("")+
  ggtitle("Time Spent Playing Video Games During Finals across Expected Grade") + 
  geom_text(aes(label = round(means, 2)), vjust = -0.5) 

# ANOVA test 
summary(aov(time ~ grade, data))

# plot distributions
par (mfrow = c(1,3))
hist(data$time[data$grade == "4"], 
     xlim = c(0, 30),
     main = "Distribution of Time for A Students",breaks = 30, 
     xlab = "Hours Spent Playing Video Games")
hist(data$time[data$grade == "3"], 
     xlim = c(0, 30),
     main = "Distribution of Time for B Students", breaks = 30,
     xlab = "Hours Spent Playing Video Games")
hist(data$time[data$grade == "2"], 
     xlim = c(0, 30),
     main = "Distribution of Time for C Students", breaks = 30,
     xlab = "Hours Spent Playing Video Games")

```

















